sonar.projectKey=dietiestates-backend
sonar.projectName=DietiEstates25 - Backend
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=test
sonar.inclusions=src/**/*.ts
sonar.test.inclusions=test/**/*.ts

sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Esclude file di configurazione e generati
sonar.exclusions=dist/**,node_modules/**,uploads/**
