sonar.projectKey=Kenobi1797_INGSW-DietiEstates25
sonar.projectName=INGSW-DietiEstates25
sonar.organization=kenobi1797
sonar.projectVersion=1.0

sonar.sources=dietiestates-backend/src,dietiestates-frontend/src
sonar.tests=dietiestates-backend/test
sonar.inclusions=dietiestates-backend/src/**/*.ts,dietiestates-frontend/src/**/*.{ts,tsx,css}
sonar.test.inclusions=dietiestates-backend/test/**/*.ts

sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=dietiestates-backend/coverage/lcov.info
sonar.typescript.lcov.reportPaths=dietiestates-backend/coverage/lcov.info
sonar.coverage.exclusions=dietiestates-frontend/**,dietiestates-backend/src/config/**,dietiestates-backend/src/controllers/**,dietiestates-backend/src/middleware/**,dietiestates-backend/src/routes/**,dietiestates-backend/src/server.ts,dietiestates-backend/src/dao/AgenziaDAO.ts,dietiestates-backend/src/dao/ImmobileDAO.ts,dietiestates-backend/src/dao/OAuthDAO.ts,dietiestates-backend/src/dto/AgenziaDTO.ts,dietiestates-backend/src/dto/ImmobileDTO.ts,dietiestates-backend/src/dto/OAuthAccountDTO.ts,dietiestates-backend/src/dto/UtenteDTO.ts,dietiestates-backend/src/utils/jwt.ts

# Esclude file di configurazione e generati
sonar.exclusions=**/dist/**,**/node_modules/**,dietiestates-backend/uploads/**,dietiestates-backend/coverage/**
